import {
  ShoppingBag,
  HeartPulse,
  Wallet,
  TrainFront,
  Filter,
  FilterX,
  Banknote,
  Utensils,
  Theater,
  Clapperboard,
  Fuel,
  CreditCard,
  Calendar,
  Home,
  History,
  LayoutGrid,
  PiggyBank,
  User,
  Wallet2,
  Pencil,
  Trash2,
  X,
  PlusCircle,
  Plus,
  IndianRupee,
  DollarSign,
  MoreVertical,
  MoreHorizontal,
  BarChart3,
  Repeat,
  Replace,
  Download,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  TrendingUp,
  TrendingDown,
  Square,
  SquareCheck,
  HandCoins,
  ChartNoAxesCombined,
  WalletCards,
} from "lucide-react";

const CategoryIcons = {
  movies: <Clapperboard />,
  shopping: <ShoppingBag />,
  food: <Utensils />,
  health: <HeartPulse />,
  utilities: <Wallet2 />,
  salary: <Wallet />,
  train: <TrainFront />,
  transport: <TrainFront />,
  theaterMask: <Theater />,
  entertainment: <Theater />,
  bank: <Banknote />,
  wallet: <Wallet />,
  card: <CreditCard />,
  calendar: <Calendar />,
  repeat: <Repeat />,
  self: <Replace />,
  fuel: <Fuel />,
  LayoutGrid: <LayoutGrid />,
};

const FreeIcons = {
  uncheckedBox:<Square />,
  checkedBox:<SquareCheck />,
  edit: <Pencil />,
  download: <Download />,
  verticalThreeDots: <MoreVertical />,
  horixzontalThreeDots: <MoreHorizontal />,
  delete: <Trash2 />,
  close1: <X />,
  addCategory: <PlusCircle />,
  add: <Plus />,
  inr: <IndianRupee />,
  usd: <DollarSign />,
  filteropen: <FilterX />,
  filterClosed: <Filter />,
};

const AccountIcons = {
  cash: <Wallet />,
  "credit card": <CreditCard />,
  savings: <PiggyBank />,
  wallet: <Wallet />,
};

const ArrowIcons = {
  left: <ArrowLeft />,
  right: <ArrowRight />,
  leftAngle: <ChevronLeft />,
  rightAngle: <ChevronRight />,
  leftDoubleAngle: <ChevronsLeft />,
  rightDoubleAngle: <ChevronsRight />,
  incArrow: <TrendingUp />,
  decArrow: <TrendingDown />,
};

const NavIcons = {
  Home: <Home />,
  Profile: <User />,
  Transactions: <History />,
  Categories: <LayoutGrid />,
  Budgets: <HandCoins />,
  Reports:<ChartNoAxesCombined />,
  Accounts1: <PiggyBank />,
  Accounts: <WalletCards />,
};

export { CategoryIcons, NavIcons, AccountIcons, FreeIcons, ArrowIcons };
